function:
  study_mapping: False
  check_for_missing_modules: True
  plot_lpGBTLoads: False
  plot_ModuleLoads: False
  produce_AllocationFile: False               
  produce_nTCsPerModuleHists: False
  
print_level: 0
output_dir: .

study_mapping:
  MappingFile: data/FeMappingV7.txt
  CMSSW_ModuleHists: data/ROverZHistograms_v11_relval_neutrino_gun_20200611.root

  #Algorithms for minimisation:
  #'random_hill_climb', 'simulated_annealing', 'save_root'
  algorithm: random_hill_climb

  #initial state configuation:
  #'random', 'example', 'data/bundles_job_best_neutrinogun_200617.npy'
  initial_state: random

  random_seed: ~
  max_iterations: 100000 

  #Definition of a minigroup:
  #'bylayer_silicon_seprated', 'bylayer', 'minimal'
  minigroup_type: 'minimal'

  #Options for use in the chi2 function
  chi2:
    include_errors_in_chi2: False
    include_max_modules_in_chi2: False
    max_modules_weighting_factor: 1000

  phisplit:
    #How to split in phi, either 'per_roverz_bin' (midpoint splits taken from CMSSW_ModuleHists file) or 'fixed'
    #If 'fixed' need to provide split values in degrees,
    #i.e. fixed point in phi at which the split should occur: 'phidivisionX_fixvalue_min' and #phidivisionY_fixvalue_max'
    #'per_roverz_bin', 'fixed'
    type: per_roverz_bin
    phidivisionX_fixvalue_min: 55 #degrees
    phidivisionY_fixvalue_max: 55 #degrees

corrections:
  ldmToHdmModuleCorrectionFile: 'data/different_moduleType_HDMInMappingFile_linkMapping.txt'
  ldmToHdmCorrectionType : 'FixedOcc'
  nTCCorrectionFile: 'data/different_nTCs_linkMapping.txt'

check_for_missing_modules:
  inCMSSW: True
  inMappingFile: True
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"

plot_lpGBTLoads:
  MappingFile: data/FeMappingV7.txt
  # V11
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"
  # V10
  # CMSSW_Silicon: "data/average_tcs_sil_v10_qg_20200331.csv"
  # CMSSW_Scintillator: "data/average_tcs_scin_v10_qg_20200331.csv"

plot_ModuleLoads:
  MappingFile: data/FeMappingV7.txt
  CMSSW_Silicon: "data/average_tcs_sil_v11_relval_ttbar_20200611.csv"
  CMSSW_Scintillator: "data/average_tcs_scin_v11_relval_ttbar_20200611.csv"

produce_AllocationFile:
  MappingFile: data/FeMappingV7.txt
  allocation: bundles_job_7058.npy
  minigroup_type: 'minimal'

produce_nTCsPerModuleHists:
  MappingFile: data/FeMappingV7.txt
  allocation: bundles_job_7058.npy
  minigroup_type: 'minimal'
  CMSSW_ModuleHists: data/nTCs_v11_relval_ttbar_20200814.root